# Alacritty configuration (TOML)
# Migrated from YAML to support latest Alacritty versions

[general]
live_config_reload = true

[window]
# dimensions of 0 mean use defaults
# dimensions = { columns = 0, lines = 0 }
padding = { x = 12, y = 12 }
dynamic_padding = true
decorations = "Full"
opacity = 1.0

[scrolling]
history = 10000
multiplier = 3

[font]
size = 11.0
normal = { family = "Iosevka Nerd Font", style = "Regular" }
bold = { family = "Iosevka Nerd Font", style = "Bold" }
italic = { family = "Iosevka Nerd Font", style = "Italic" }
offset = { x = 1, y = 0 }
glyph_offset = { x = 0, y = 0 }

[cursor]
# style can be: Block, Underline, Beam
style = { shape = "Block" }`
unfocused_hollow = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = false

[bell]
animation = "EaseOutExpo"
duration = 0
color = "0xffffff"

[colors.primary]
background = "0x000000"
foreground = "0xeaeaea"

[colors.normal]
black   = "0x000000"
red     = "0xd54e53"
green   = "0xb9ca4a"
yellow  = "0xe6c547"
blue    = "0x7aa6da"
magenta = "0xc397d8"
cyan    = "0x70c0ba"
white   = "0xeaeaea"

[colors.bright]
black   = "0x666666"
red     = "0xff3334"
green   = "0x9ec400"
yellow  = "0xe7c547"
blue    = "0x7aa6da"
magenta = "0xb77ee0"
cyan    = "0x54ced6"
white   = "0xffffff"

# Mouse bindings
[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"
